services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ${HOME}/pdf:/app/pdf  # 호스트의 pdf 폴더를 컨테이너에 연결
      - ${HOME}/sqlite3:/app/sqlite3  # 호스트의 sqlite3 폴더를 컨테이너에 연결
    environment:
      - PDF_FOLDER=/app/pdf
      - DB_FOLDER=/app/sqlite3  # 환경 변수도 sqlite3 폴더로 변경
    networks:
      - flask  # flask 네트워크에 연결

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Let's Encrypt 인증서 경로
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - flask
    networks:
      - flask  # flask 네트워크에 연결

networks:
  flask:
    driver: bridge  # 동일한 네트워크에 두 서비스를 연결
