services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ${HOME}/sqlite3:/app/sqlite3  # 호스트의 sqlite3 폴더를 컨테이너에 연결
    environment:
      - PDF_FOLDER=/app/pdf
      - DB_FOLDER=/app/sqlite3  # 환경 변수도 sqlite3 폴더로 변경
      - TZ=Asia/Seoul  # 타임존 설정
      - REDIS_HOST=redis  # Redis 호스트 이름
      - REDIS_PORT=6379  # Redis 포트
    networks:
      - flask  # flask 네트워크에 연결
    depends_on:
      - redis  # Redis 서비스가 먼저 시작되도록 설정

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # nginx.conf 추가
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Let's Encrypt 인증서 경로
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - flask
    environment:
      - TZ=Asia/Seoul  # 타임존 설정
    networks:
      - flask  # flask 네트워크에 연결

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Redis 기본 포트
    restart: unless-stopped
    networks:
      - flask  # flask 네트워크에 연결

networks:
  flask:
    driver: bridge  # 동일한 네트워크에 두 서비스를 연결
