services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ${HOME}/sqlite3:/app/sqlite3  # 호스트의 sqlite3 폴더를 컨테이너에 연결
      - ${HOME}/wallet:/app/wallet  #wallet
      - ./static:/app/static  # 프로젝트 폴더의 static 디렉토리를 컨테이너에 연결
    environment:
      - PDF_FOLDER=/app/pdf
      - DB_FOLDER=/app/sqlite3  # 환경 변수도 sqlite3 폴더로 변경
      - TZ=Asia/Seoul  # 타임존 설정
    networks:
      - flask  # flask 네트워크에 연결

networks:
  flask:
    driver: bridge  # 동일한 네트워크에 두 서비스를 연결
