services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask
    networks:
      - flask

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ${HOME}/sqlite3:/app/sqlite3
      - ${HOME}/wallet:/app/wallet
      - ./static:/app/static
    environment:
      - PDF_FOLDER=/app/pdf
      - DB_FOLDER=/app/sqlite3
      - TZ=Asia/Seoul
    networks:
      - flask

networks:
  flask:
    driver: bridge
