services:
  flask-pdf-server:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ${HOME}/pdf:/app/pdf  # 호스트의 pdf 폴더를 컨테이너에 연결
      - ${HOME}/sqlite3:/app/sqlite3  # 호스트의 sqlite3 폴더를 컨테이너에 연결
    environment:
      - PDF_FOLDER=/app/pdf
      - DB_FOLDER=/app/sqlite3  # 환경 변수도 sqlite3 폴더로 변경

networks:
  flask-network:
    driver: bridge